### ISSUE TITLE
How to pass  regexner

### ISSUE THREAD

**Issue by satishkumarkt** [gerardobort/node-corenlp#30]
How to pass my own regexner training data to server?

I am doing as below  but it not shows my NER can you please provide some Example
I would like to identify martendail  as  MATERIAL

**node file**
require("babel-polyfill");
const corenlp = require("corenlp");
const CoreNLP = corenlp.default; // convenient when not using `import`

const connector = new corenlp.ConnectorServer({
    dsn: 'http://localhost:9000',
});

const props = new corenlp.Properties();
props.setProperty('annotators', 'tokenize, ssplit, pos, lemma, parse, ner, regexner');
props.setProperty('regexner.mapping', 'training.txt');

const pipeline = new corenlp.Pipeline(props, 'English', connector);
const sent = new CoreNLP.simple.Sentence(
    'martendail 20000 Julia Eileen Gillard (born 29 September 1961) is an Australian politician who was the Prime Minister of Australia.'
);

async function f(){
	// performs the call to corenlp (in this case via http)
	await pipeline.annotate(sent);

	// constituency parse tree representation
	const tree = CoreNLP.util.Tree.fromSentence(sent);

	// traverse the tree leaves and print some props
	tree.visitLeaves(node =>
	  console.log(node.word(), node.token().ner()));
}

process.on('unhandledRejection', error => {
    console.log('unhandledRejection', error.message);
});

f();

**output**

martendail O
20000 NUMBER
Julia PERSON
Eileen PERSON
Gillard PERSON
-LRB- O
born O
29 DATE
September DATE
1961 DATE
-RRB- O
is O
an O
Australian NATIONALITY
politician TITLE
who O
was O
the O
Prime TITLE
Minister TITLE
of O
Australia COUNTRY

**training.txt** 

( /martendail/ )	MATERIAL
( /martendail/ [ner:NUMBER] )	MATERIAL

**Comment by gerardobort** [comment]
Hi @satishkumarkt,

Have you placed `training.txt` within the model's path?
It is required to put that file in the same folder as your CoreNLP `.properties` model file.  If you're using the default english `.jar` model, you have to either extract the `.properties` into the same folder of your `training.txt` file,  or put that `.txt` inside the `.jar` (as it were a regular zip) at the same level.
This setup is a bit tricky, but has more to do on how to configure CoreNLP.  I left a guide, step by step, that includes RegexNER setup here (https://github.com/gerardobort/nodeconfar2017-nlp-workshop, https://github.com/gerardobort/nodeconfar2017-nlp-workshop/tree/master/src/model-train), it's based on a workshop exercise, and I apologize is in spanish 🙃 .

Cheers!

**Comment by satishkumarkt** [comment]
Thanks @gerardobort 

my problem resolved while placing the  .txt inside the .jar
