### ISSUE TITLE
Trees don't double link properly

### ISSUE THREAD

**Issue by LocustEater** [gerardobort/node-corenlp#41]
Trees only add a parent to direct children of the root. Looks like the recursive call in tree.js _transformTree doesn't pass the doubleLink bool, so all children below root's immediate children don't get a parent. 

Line 259:
`const childNode = this._transformTree(n);`
Should be:
`const childNode = this._transformTree(n, doubleLink);`

**Comment by gerardobort** [comment]
Thanks @LocustEater, yes, it's a bug... will fix that soon.

**Comment by gerardobort** [comment]
@LocustEater fixed in version `1.4.3`
