### ISSUE TITLE
add support for username/password authentication?

### ISSUE THREAD

**Issue by Luke-Tan** [gerardobort/node-corenlp#43]
Stanford CoreNLP allows username and password params when starting up the server. Is it possible to use this for authentication within the node-corenlp framework?

**Comment by gerardobort** [comment]
Hi @Luke-Tan,

Not possible currently, but I'll take it into account for upcoming updates.  If you want to submit a PR, I'd be glad to merge it.

Thanks,

**Comment by Luke-Tan** [comment]
Hi @gerardobort,

Do you have any reccomended ways to add authentication to make calls to the NLP server? Basically I have set up a coreNLP server and my node app queries it with this library. Any idea how I could restrict usage of the server to my app only and not other people who may know the url to my app? I am fairly new to server-side programming and its best practices. Thanks!

**Comment by roberthaidari** [comment]
Hey @gerardobort I wanted to do a PR to enable this, it's just ~10 additional lines of simple code in connector-server.js
```
const config = {
  dsn: 'http://localhost:9000',
  auth: {
    user: null,
    pass: null,
  },
};
```
And an if statement at the bottom.  What's the best way to push my branch (I don't have permissions)?

**Comment by gerardobort** [comment]
Hi @roberthaidari, You can fork the repo, push the changes to a branch on your copy and open a PR against this copy.  I'd be glad to accept contributions!

**Comment by gerardobort** [comment]
Hi @Luke-Tan, @roberthaidari, the basic auth support it's been added to version `1.4.4`.  Late but safe!
