### ISSUE TITLE
Properties not forwarded to server?

### ISSUE THREAD

**Issue by DiegoGLagash** [gerardobort/node-corenlp#44]
Hi,

I'm trying to set a property to the ssplit with the following code:

```
const props = new corenlp.Properties({
  annotators: 'tokenize,ssplit',
});
props.setProperty('ssplit.newlineIsSentenceBreak', 'always');
```

But the property is being ignored during processing, is there any reason for this? Do you know if this is supported?

**Comment by gerardobort** [comment]
Hi @DiegoGLagash,

In general, they are being forwarded, and it seems to be the case here too.  But take into account that `CoreNLPServer` gives precedence to the settings in this order:

1. `.properties` file that is inside the `jar` (if many `jar`files are included, the last one)
2. `.properties` file passed through `-props` from CLI
3. properties passed through http params (current case)

So, probably you have that setting overriden in either 1 or 2.
