### ISSUE TITLE
Assert: Semgrex requires class TokenizerAnnotator extends _annotator2.default

### ISSUE THREAD

**Issue by anudeike** [gerardobort/node-corenlp#60]
Not entirely sure what this means.  Here is a code snippet:
`// get the properties and [pipeline](URL)
const props = new CoreNLP.Properties({
    annotators: 'tokenize,ssplit,pos,lemma,ner,parse',
}); 

// create a new pipline, should only be created once per request
const pipeline = new CoreNLP.Pipeline(props, 'English');

// must use the default
const expr = new CoreNLP.default.simple.Expression(
    'Jon Snow eats snow.',
    '{ner:PERSON}=who <nsubj ({pos:VBZ}=action >dobj {}=what)');

pipeline.annotateSemgrex(expr, true)
    .then(expr => expr.sentence(0).matches().map(match => {
        console.log('match', match.group('who'), match.group('action'), match.group('what'));
    })).catch(err => {
        console.log('err', err)
    })`

**Comment by anudeike** [comment]
This is from the example on npm btw

**Comment by gerardobort** [comment]
Hi @anudeike,

I see an annotator missing on your annotators list that is mandatory for Semgrex: `depparse`.
It looks the error reported should be longer, as is intended to list all the annotators required: https://github.com/gerardobort/node-corenlp/blob/349f44bb7c856639797286e59331db5a28373e91/src/pipeline.js#L136

Let me know if this helps.

Thanks,

**Comment by anudeike** [comment]
Ok, this seems to have fixed my problem
