### ISSUE TITLE
<h1>404 Not Found</h1>No context found for request

### ISSUE THREAD

**Issue by anudeike** [gerardobort/node-corenlp#61]
I'm trying to connect to this endpoint: https://corenlp.run/ instead of my localhost (for computer speed reasons). 

I got the above response when I tried creating a custom connector. Not sure what it means, but the endpoint seems correct. 

// Setting the connector up
``` const connector = new CoreNLP.ConnectorServer({ dsn: "https://corenlp.run/" }) ```

// passing it into the pipeline
```const pipeline = new CoreNLP.Pipeline(props, lang, connector);```

These are the two most relevant lines of code. Not sure if more is needed.

Thanks for all the help.

**Comment by gerardobort** [comment]
Hi @anudeike,

There's an extra slash on the dsn that should be removed.
```
// this should work
const connector = new CoreNLP.ConnectorServer({ dsn: "https://corenlp.run" })
```

Cheers!

**Comment by anudeike** [comment]
Worked! Thank you, I can't believe it was that simple. Why could I not include that backslash?

**Comment by gerardobort** [comment]
Awesome! I'm glad to have helped.
